# ----------------------------------------------------------------------------
# Site settings
# ----------------------------------------------------------------------------

title: Bello Muhammad Abdullahi
first_name: Bello
middle_name: Muhammad
last_name: Abdullahi
email: b.abdullahi@lancaster.ac.uk
description: > 
  Bello Muhammad Abdullahi is a PhD Economics Student at Lancaster University. 
  His research focuses on macroeconomics economics, development and monetary economics.


lang: en
icon: true

url: https://bello-abdullahi.github.io
baseurl: ""

# ----------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------

# code highlighter theme
highlight_theme_light: github   # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native    # https://github.com/jwarby/jekyll-pygments-themes

# repo color theme
repo_theme_light: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat    # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed  # https://github.com/ryo-ma/github-profile-trophy

# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: true

# ----------------------------------------------------------------------------
# Social integration
# ----------------------------------------------------------------------------

github_username: Bello-Abdullahi
twitter_username: Muhammad_Bell0
linkedin_username: Bello Muhammad Abdullahi
scholar_userid: FONaAoAAAAAJ
orcid_id: 0000-0001-5075-1812

contact_note: >
  The best way to reach me is by email.

# ----------------------------------------------------------------------------
# Layout
# ----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true


# ----------------------------------------------------------------------------
# Announcements / posts
# ----------------------------------------------------------------------------

announcements:
  enabled: false

latest_posts:
  enabled: false

# ----------------------------------------------------------------------------
# Optional features
# ----------------------------------------------------------------------------

enable_google_analytics:    false  # enables google analytics
enable_cronitor_analytics: false  # enables cronitor RUM analytics
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
enable_masonry:             true   # enables automatic project cards arrangement
enable_math:                true   # enables math typesetting (uses MathJax)
enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enable_darkmode:            true   # enables switching between light/dark modes
enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)
enable_progressbar:         true   # enables a horizontal progress bar linked to the vertical scroll position


